### ISSUE TITLE
Seems like you CAN'T use "admin" for both username and password to access Kiali

### ISSUE THREAD

**Issue by maxsel** [peterj/workshop-material#7]
I am following https://github.com/peterj/jfuture/tree/master/istio#installing-istio and trying to use "admin" for both username and password to access Kiali (for some reason the trick with EOF didn't worked for me that time, so I'm using static file):

`$ kubectl apply -f /Users/maxsel/jfuture/istio/kiali-secret.yml`
> Error from server (BadRequest): error when creating "/Users/maximselyuk/jfuture/istio/kiali-secret.yml": Secret in version "v1" cannot be handled as a Secret: v1.Secret.Data: decode base64: illegal base64 data at input byte 4, error found in #10 byte of ...|e":"admin","username|..., bigger context ...|{"apiVersion":"v1","data":{"passphrase":"admin","username":"admin"},"kind":"Secret","metadata":{"|...

After giving up with plain "admin" value and falling back to original value (`YWRtaW4=` - base64-encoded "admin") in kiali-secret.yml everything works fine:

`$ kubectl apply -f /Users/maxsel/jfuture/istio/kiali-secret.yml`
> secret/kiali created

Not sure what's the reason, maybe newer versions of kubectl doesn't allow that?

**Comment by peterj** [comment]
The values in secrets need to be base64 encoded. I re-read the way I've written it and it does seem confusing. I have updated it!
